apiVersion: apps/v1
kind: Deployement
metadata:
  name: papache-rob
  namespace: web-rob
  labels:
    app: papache-rob
spec:
  replicas:
  selector:
    matchLabels:
      app: papache-rob
  template:
    metadata:
      labels:
        app: papache-rob
    spec:
      containers:
        - name: papache-rob
          image: httpd:2.4.62-alpine3.21
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: papache-rob-svc
  namespace: web-rob
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 8085
      targetPort: 80
      protocol: TCP
  selector:
    app: papache-rob
